### ISSUE TITLE
Add .babelrc to .npmignore

### ISSUE THREAD

**Issue by ashl1** [w33ble/simpleutils#1]
## The case
* some of libs in npm registry provides only ES6 builds
* we want to support browsers with ES5 builds

## Solution we use
* enable `babel` for `node_modules` directory

## Problem
While Babel is run for files provided by npm, the Babel configuration is presented in the package.json file. But the already babelified js file will be used. Threfore our (external) Babel tries to use (internal) Babel config. The configuration between your package and our Babel might be different.

## Decision
Could you add the `.babelrc` file to `.npmignore`? And maybe `src/` directory?
If user wants to develop an app he will use Git sources with `.babelrc`. If he simply wants to use the builded form of your package, this won't be affected by the internal Babel settings.

**Comment by w33ble** [comment]
I hadn't heard of anyone using babel to build node modules before. That's pretty interesting, glad it works for you. I added .babelrc to .npmignore and published 1.0.2 (and 2.0.0 with another change I've been wanting to make). If it doesn't solve your issue, feel free to follow up here or open another issue. 

EDIT: 1.0.2 was a bad build, 1.0.3+ is what you'll want to use.

**Comment by ashl1** [comment]
You can read the following article: Look at https://philipwalton.com/articles/deploying-es2015-code-in-production-today/
But we start to think we need to build source of all libs we use because almost all libs are distributed compiled to ES5.

**Comment by w33ble** [comment]
Yeah, npm is in a weird flux state right now. Thanks for the reference and for opening the issue.
